name: prettier

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm install --ignore-scripts
      - run: npm run format:check
